export const Questions = [
    {
      prompt: "What is your name?",
      optionA: "Ali",
      optionB: "Hassan",
      optionC: "Ahmed",
      optionD: "Yousuf",
      asnwer: "A",
    },
    {
      prompt: "What's Your Profession?",
      optionA: "Teacher",
      optionB: "Doctor",
      optionC: "Engineer",
      optionD: "Tailor",
      asnwer: "C",
    },
    {
      prompt: "Which one is a javascript library?",
      optionA: "React",
      optionB: "Angular",
      optionC: "Python",
      optionD: "Java",
      asnwer: "A",
    },
    {
      prompt: "Which one is not a language?",
      optionA: "C",
      optionB: "C++",
      optionC: "Java",
      optionD: "Html",
      asnwer: "D",
    },
    {
      prompt: "Which team can't qualify to SemiFinal  WC21?",
      optionA: "India",
      optionB: "Australia",
      optionC: "England",
      optionD: "Pakistan",
      asnwer: "A",
    },
    {
      prompt: "Kiwi is only found in ?",
      optionA: "Dubai",
      optionB: "Pakistan",
      optionC: "New Zealand",
      optionD: "America",
      asnwer: "C",
    },
    {
      prompt: "Most popular Programming Language?",
      optionA: "Python",
      optionB: "Javascript",
      optionC: "Both",
      optionD: "None",
      asnwer: "C",
    },
  ];